require 'test/unit'
require_relative 'string_plus_test'
require_relative 'string_format_test'
require_relative 'round_down_diff_test'
require_relative 'calc_tax_test'
require_relative 'compare_length_test'
require_relative 'right_triangle_test'
