require 'test/unit'
require_relative '01_type_test'
require_relative '02_expression_test'
require_relative '03_function_test'
require_relative '04_array_test'
require_relative '05_exception_test'
require_relative '06_if_test'
