require 'test/unit'
require_relative 'lesseq_more_ten_test'
require_relative 'judge_number_position_test'
require_relative 'grade_test'
require_relative 'is_adult_test'
require_relative 'is_number_test'
require_relative 'even_test'
require_relative 'calc_bmi_test'
