require 'test/unit'
require_relative 'pre_pre_last_test'
require_relative 'sorted_unique_array_test'
require_relative 'sum_test'
require_relative 'count_trailing_zero_test'
require_relative 'validate_isbn10_test'
require_relative 'max_index_test.rb'
require_relative 'sort_3_num_test.rb'
